// Trusted statement bridge generator (§9.3 step 3, step 7).
// The bridge re-states each obligation with the FROZEN contract type and
// binds it to a fully qualified candidate declaration; it also states that
// the proof-bound definitions EQUAL the values the fixed-harness binary
// produced (export + planner fixtures), checked by the Lean kernel (`decide`).

import type { PlannerView, StepSpec, WorkflowDef } from "../../packages/protocol/kernel-types.ts";

export type Recipe = "pin_only" | "ordering_only" | "planner_equivalent";

export interface Obligation {
  id: string;             // P01..P05
  decl: string;           // candidate declaration (fully qualified)
  statement: string;      // frozen expected type (Lean source)
  scope: "general" | "finite-kernel-reduced";
}

export class BridgeError extends Error {
  constructor(msg: string) {
    super(msg);
    this.name = "BridgeError";
  }
}

export function obligationsFor(recipe: Recipe): Obligation[] {
  const obs: Obligation[] = [
    { id: "P01", decl: "_root_.FactoryPkg.p01", scope: "finite-kernel-reduced",
      statement: "_root_.Factory.Contracts.P01 _root_.FactoryPkg.workflows" },
    { id: "P02", decl: "_root_.FactoryPkg.p02", scope: "general",
      statement: "_root_.Factory.Contracts.P02 _root_.FactoryPkg.plan" },
    { id: "P03", decl: "_root_.FactoryPkg.p03", scope: "finite-kernel-reduced",
      statement: "_root_.Factory.Contracts.P03 _root_.FactoryPrev.workflows _root_.FactoryPkg.workflows" },
  ];
  if (recipe === "ordering_only") {
    obs.push({ id: "P04", decl: "_root_.FactoryPkg.p04", scope: "finite-kernel-reduced",
      statement: "_root_.Factory.Contracts.P04OrderingOnly _root_.FactoryPrev.workflows _root_.FactoryPkg.workflows" });
  } else if (recipe === "planner_equivalent") {
    obs.push({ id: "P04", decl: "_root_.FactoryPkg.p04", scope: "finite-kernel-reduced",
      statement: "_root_.Factory.Contracts.P04Unchanged _root_.FactoryPrev.workflows _root_.FactoryPkg.workflows" });
    obs.push({ id: "P05", decl: "_root_.FactoryPkg.p05", scope: "general",
      statement: "_root_.Factory.Contracts.P05 _root_.FactoryPrev.plan _root_.FactoryPkg.plan" });
  }
  return obs;
}

const SAFE_STR = /^[\x20-\x7e]*$/;

export function leanStr(s: string): string {
  if (!SAFE_STR.test(s)) throw new BridgeError(`non-printable-ASCII string in export: ${JSON.stringify(s)}`);
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

function leanNat(s: string): string {
  if (!/^(0|[1-9][0-9]{0,18})$/.test(s)) throw new BridgeError(`bad natural ${s}`);
  return s;
}

const ROLE: Record<string, string> = {
  author: "author", materialize: "materialize", build: "build", prove: "prove",
  reproduce: "reproduce", refute: "refute", summarize: "summarize",
};
const KIND: Record<string, string> = {
  package_audit: "packageAudit", change_author: "changeAuthor", change_evaluate: "changeEvaluate",
};

function leanList(xs: string[]): string {
  return "[" + xs.join(", ") + "]";
}

function stepLit(s: StepSpec): string {
  const role = ROLE[s.role];
  if (!role) throw new BridgeError(`unknown role ${s.role}`);
  const inputs = s.inputs.map((b) => {
    const src = b.source.type === "job_input"
      ? "_root_.Factory.InputSource.jobInput"
      : `(_root_.Factory.InputSource.stepOutput ${leanStr(b.source.step)})`;
    return `({ name := ${leanStr(b.name)}, source := ${src} } : _root_.Factory.InputBinding)`;
  });
  return `({ id := ${leanStr(s.id)}, role := _root_.Factory.Role.${role}, after := ${leanList(s.after.map(leanStr))}, ` +
    `inputs := ${leanList(inputs)}, prompt := ${leanStr(s.prompt)}, retries := ${leanNat(s.retries)} } : _root_.Factory.StepSpec)`;
}

export function workflowLit(w: WorkflowDef): string {
  const kind = KIND[w.kind];
  if (!kind) throw new BridgeError(`unknown kind ${w.kind}`);
  return `({ kind := _root_.Factory.JobKind.${kind}, steps := ${leanList(w.steps.map(stepLit))}, ` +
    `maxParallel := ${leanNat(w.max_parallel)} } : _root_.Factory.WorkflowDef)`;
}

export function viewLit(v: PlannerView): string {
  return `({ workflow := ${workflowLit(v.workflow)}, ready := ${leanList(v.ready.map(leanStr))}, ` +
    `slots := ${leanNat(v.slots)} } : _root_.Factory.PlannerView)`;
}

export interface BridgeInput {
  recipe: Recipe;
  exports: WorkflowDef[];
  fixtures: { view: PlannerView; plan: string[] }[];
}

export function bridgeSource(inp: BridgeInput): { bridge: string; audit: string; decls: string[] } {
  const obs = obligationsFor(inp.recipe);
  const lines: string[] = [
    "-- GENERATED by the protected verifier. Trusted statement bridge.",
    "import Factory.PackageContracts",
    "import FactoryPkg.Package",
    "import FactoryPkg.Planner",
    "import FactoryPkg.Proofs",
    "import FactoryPrev.Package",
    "import FactoryPrev.Planner",
    "namespace FactoryBridge",
  ];
  const decls: string[] = [];
  for (const o of obs) {
    lines.push(`theorem ${o.id} : ${o.statement} := ${o.decl}`);
    decls.push(`FactoryBridge.${o.id}`);
  }
  lines.push(`theorem EXPORT : _root_.FactoryPkg.workflows = ${leanList(inp.exports.map(workflowLit))} := by decide`);
  decls.push("FactoryBridge.EXPORT");
  inp.fixtures.forEach((f, i) => {
    lines.push(`theorem FIX_${i} : _root_.FactoryPkg.plan ${viewLit(f.view)} = ${leanList(f.plan.map(leanStr))} := by decide`);
    decls.push(`FactoryBridge.FIX_${i}`);
  });
  lines.push("end FactoryBridge", "");
  const audit = ["import FactoryBridge", ...decls.map((d) => `#print axioms ${d}`), ""].join("\n");
  return { bridge: lines.join("\n"), audit, decls };
}

export const APPROVED_AXIOMS = new Set(["propext", "Classical.choice", "Quot.sound"]);

export interface AxiomReport { decl: string; axioms: string[]; ok: boolean }

/** Parse `#print axioms` output strictly: every expected decl exactly once. */
export function parseAxioms(text: string, decls: string[]): { reports: AxiomReport[]; problems: string[] } {
  const problems: string[] = [];
  const found = new Map<string, string[]>();
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    let m = /^'([^']+)' depends on axioms: \[(.*)\]$/.exec(line);
    if (m) {
      if (found.has(m[1])) problems.push(`duplicate axiom report for ${m[1]}`);
      found.set(m[1], m[2].split(",").map((s) => s.trim()).filter(Boolean));
      continue;
    }
    m = /^'([^']+)' does not depend on any axioms$/.exec(line);
    if (m) {
      if (found.has(m[1])) problems.push(`duplicate axiom report for ${m[1]}`);
      found.set(m[1], []);
      continue;
    }
    problems.push(`unexpected audit output: ${line.slice(0, 200)}`);
  }
  const reports: AxiomReport[] = decls.map((d) => {
    const ax = found.get(d);
    if (!ax) {
      problems.push(`no axiom report for ${d}`);
      return { decl: d, axioms: [], ok: false };
    }
    const bad = ax.filter((a) => !APPROVED_AXIOMS.has(a));
    if (bad.length) problems.push(`${d} depends on unapproved axioms: ${bad.join(", ")}`);
    return { decl: d, axioms: ax, ok: bad.length === 0 };
  });
  for (const k of found.keys()) if (!decls.includes(k)) problems.push(`unexpected report for ${k}`);
  return { reports, problems };
}
